### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time

### ISSUE THREAD

**Issue by hoflz5** [rodrigo-brito/backtrader-binance-bot#10]
`binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}`

I suggest adding these options to the broker_config:

```
'options': {
        'adjustForTimeDifference': True,
    },

```

**Comment by rodrigo-brito** [comment]
This project is just an example of usage, it is not maintained and not ready to production.
